### ISSUE TITLE
AddAttachment/RemoveAttachment are not synchronized

### ISSUE THREAD

**Issue by DamienSAVOYAT** [mathieumack/NoSqlRepositories#35]
When we remove attachment associate to an entity and then we add the same attachment, there is ane exception (CouchbaseLiteException (POSIXDomain / 13): Permission denied.) 

This is because RemoveAttachment don't really remove, it just set blob to null and AddAttachment add systematically even if there is already an existing blob.

**Comment by mathieumack** [comment]
Nothing to do, reproduced steps doe not confirm a problem from the API.
